# The port on which the Pivot server will listen on.
port: 9095

clusters:
  - name: druid
    type: druid

    # A Druid broker node that can serve data (only used if you have Druid based data source)
    host: localhost:8082

    # Use SegmentMetadataQuery for introspection, rather than Broker GET routes.
    useSegmentMetadata: true

    # Background introspection frequency (in ms)
    # - Set to '0' to disable background introspection.
    sourceListRefreshInterval: 0

    # Foreground introspection
    # Checks for new dataSources every time Pivot is loaded (default: false)
    sourceListRefreshOnLoad: true

# The data sources that you have configured, these will appear, in order, inside the navigation menu of Pivot
# In general there can be two types of 'engine':
#   - native: a JSON file that is crunched within plywood itself (useful for small datasets and testing)
#   - druid: a Druid dataSource
dataSources:
  - name: wikiticker
    title: Wikiticker Quickstart
    engine: druid # Set the engine to druid
    source: wikiticker # The druid dataSource
    
    introspection: no-autofill

    refreshRule:
      rule: query
      refresh: PT1H

    defaultPinnedDimensions:
      - page
      - user
      - namespace

    attributeOverrides:
      - name: commentLength
        type: NUMBER

      - name: deltaBucket
        type: NUMBER      

    dimensions:
      - name: __time
        kind: time

      - name: page

      - name: user

      - name: channel

      - name: namespace

      - name: comment

      - name: cityName

      - name: countryName

      - name: regionName

      - name: commentLength
        kind: number

      - name: deltaBucket
        kind: number

      - name: metroCode

      - name: regionIso
        title: Region ISO
        expression: $regionIsoCode

      - name: countryIso
        title: Country ISO
        expression: $countryIsoCode

      - name: flags

      - name: diffUrl

      - name: isNew
        kind: boolean

      - name: isMinor
        kind: boolean

      - name: isRobot
        kind: boolean

      - name: isUnpatrolled
        kind: boolean

      - name: isAnonymous
        kind: boolean

    measures:
      - name: count
        title: Edits
        expression: $main.sum($count)

      - name: delta

      - name: avg_delta
        expression: $main.sum($delta) / $main.sum($count)

      - name: added

      - name: avg_added
        expression: $main.sum($added) / $main.sum($count)

      - name: deleted

      - name: avg_deleted
        expression: $main.sum($deleted) / $main.sum($count)

      - name: unique_users
        title: Unique Users
        expression: $main.countDistinct($user_unique)

  - name: wikiticker-kafka
    title: Wikiticker Kafka Tutorial
    engine: druid # Set the engine to druid
    source: wikiticker-kafka # The druid dataSource
    
    introspection: no-autofill

    refreshRule:
      rule: query
      refresh: PT5S

    defaultPinnedDimensions:
      - page
      - user
      - namespace

    attributeOverrides:
      - name: commentLength
        type: NUMBER

      - name: deltaBucket
        type: NUMBER      

    dimensions:
      - name: __time
        kind: time

      - name: page

      - name: user

      - name: channel

      - name: namespace

      - name: comment

      - name: cityName

      - name: countryName

      - name: regionName

      - name: commentLength
        kind: number

      - name: deltaBucket
        kind: number

      - name: metroCode

      - name: regionIso
        title: Region ISO
        expression: $regionIsoCode

      - name: countryIso
        title: Country ISO
        expression: $countryIsoCode

      - name: flags

      - name: diffUrl

      - name: isNew
        kind: boolean

      - name: isMinor
        kind: boolean

      - name: isRobot
        kind: boolean

      - name: isUnpatrolled
        kind: boolean

      - name: isAnonymous
        kind: boolean

    measures:
      - name: count
        title: Edits
        expression: $main.sum($count)

      - name: delta

      - name: avg_delta
        expression: $main.sum($delta) / $main.sum($count)

      - name: added

      - name: avg_added
        expression: $main.sum($added) / $main.sum($count)

      - name: deleted

      - name: avg_deleted
        expression: $main.sum($deleted) / $main.sum($count)

      - name: unique_users
        title: Unique Users
        expression: $main.countDistinct($user_unique)


  - name: metrics
    title: Metrics Quickstart
    engine: druid # Set the engine to druid
    source: metrics # The druid dataSource

    refreshRule:
      rule: query
      refresh: PT5S

    dimensions:
      - name: __time
        kind: time

    measures:
      - name: count
        title: Count
        expression: $main.sum($count)

      - name: value_sum
        title: Sum
        expression: $main.sum($value_sum)

      - name: value_avg
        title: Average
        expression: $main.sum($value_sum) / $main.sum($count)

      - name: value_min
        title: Min
        expression: $main.min($value_min)

      - name: value_max
        title: Max
        expression: $main.max($value_max)


  - name: metrics-kafka
    title: Metrics Kafka Tutorial
    engine: druid # Set the engine to druid
    source: metrics-kafka # The druid dataSource

    refreshRule:
      rule: query
      refresh: PT5S

    dimensions:
      - name: __time
        kind: time

    measures:
      - name: count
        title: Count
        expression: $main.sum($count)

      - name: value_sum
        title: Sum
        expression: $main.sum($value_sum)

      - name: value_avg
        title: Average
        expression: $main.sum($value_sum) / $main.sum($count)

      - name: value_min
        title: Min
        expression: $main.min($value_min)

      - name: value_max
        title: Max
        expression: $main.max($value_max)
